### ISSUE TITLE
Failed to compile by new version gcc (-Werror=misleading-indentation)

### ISSUE THREAD

**Issue by yanlinlin82** [lastz/lastz#17]
I tried to build from source, and got the following errors:

```
gcc -c -O3 -Wall -Wextra -Werror -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DVERSION_MAJOR="\"1"\" -DVERSION_MINOR="\"04"\" -DVERSION_SUBMINOR="\"01"\" -DREVISION_DATE="\"20190503"\" -DSUBVERSION_REV="\""\" -Dscore_type=\'I\' infer_scores.c -o infer_scores.o
infer_scores.c: In function ‘write_scores’:
infer_scores.c:1417:3: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
   if (withGapScores) fprintf (f, "# gapped_threshold = %s\n", score_thresh_to_string (&params->gappedThreshold));
   ^~
infer_scores.c:1418:22: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
                      fprintf (f, "# x_drop           = " scoreFmtSimple "\n", params->xDrop);
                      ^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:94: infer_scores.o] Error 1
```

Parameters '-Wno-misleading-indentation -Wno-implicit-fallthrough' should be added to `src/Makefile`.

**Comment by rsharris** [comment]
Thanks for reporting that.

I can understand why -Wno-misleading-indentation would affect this, but not why -Wno-implicit-fallthrough would. Is there some other part of the source code that triggers an implicit-fallthrough warning?

**Comment by yanlinlin82** [comment]
Yes, without '-Wno-implicit-fallthrough', it prompts the following warnings/errors:

```
gcc -c -O3 -Wall -Wextra -Werror -Wno-misleading-indentation -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DVERSION_MAJOR="\"1"\" -DVERSION_MINOR="\"04"\" -DVERSION_SUBMINOR="\"01"\" -DREVISION_DATE="\"20190503"\" -DSUBVERSION_REV="\""\" -Dscore_type=\'I\' utilities.c -o utilities.o
genpaf.c: In function ‘print_genpaf_align’:
genpaf.c:850:8: error: this statement may fall through [-Werror=implicit-fallthrough=]
     if (strand2 == '-')
        ^
genpaf.c:856:4: note: here
    case genpafStart2:
    ^~~~
genpaf.c:860:8: error: this statement may fall through [-Werror=implicit-fallthrough=]
     if (strand2 == '-')
        ^
genpaf.c:866:4: note: here
    case genpafStart2Zero:
    ^~~~
genpaf.c:873:8: error: this statement may fall through [-Werror=implicit-fallthrough=]
     if (strand2 == '-')
        ^
genpaf.c:879:4: note: here
    case genpafEnd2:
    ^~~~
genpaf.c: In function ‘print_genpaf_match’:
genpaf.c:1535:8: error: this statement may fall through [-Werror=implicit-fallthrough=]
     if (strand2 == '-')
        ^
genpaf.c:1541:4: note: here
    case genpafStart2:
    ^~~~
genpaf.c:1545:8: error: this statement may fall through [-Werror=implicit-fallthrough=]
     if (strand2 == '-')
        ^
genpaf.c:1551:4: note: here
    case genpafStart2Zero:
    ^~~~
genpaf.c:1558:8: error: this statement may fall through [-Werror=implicit-fallthrough=]
     if (strand2 == '-')
        ^
genpaf.c:1564:4: note: here
    case genpafEnd2:
    ^~~~
gcc -c -O3 -Wall -Wextra -Werror -Wno-misleading-indentation -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DVERSION_MAJOR="\"1"\" -DVERSION_MINOR="\"04"\" -DVERSION_SUBMINOR="\"01"\" -DREVISION_DATE="\"20190503"\" -DSUBVERSION_REV="\""\" -Dscore_type=\'I\' dna_utilities.c -o dna_utilities.o
utilities.c: In function ‘hassock_hash’:
utilities.c:1814:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
   case 3: h ^= *(--data) << 16;
             ^~
utilities.c:1815:3: note: here
   case 2: h ^= *(--data) << 8;
   ^~~~
utilities.c:1815:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
   case 2: h ^= *(--data) << 8;
             ^~
utilities.c:1816:3: note: here
   case 1: h ^= *(--data);
   ^~~~
```

**Comment by rsharris** [comment]
Thanks for pointing those out.

Would '__attribute__ ((fallthrough))' work on your compiler?

I'm like to avoid turning off a whole class of warnings, because the intent of the warnings is to get me to look at the code and make sure it will do what is intended. In the case of these fall-thrus, they are intentional (I've updated the ones in utilities.c so the human reader can tell that). I'd like to just tell the compiler these are intentional. Which I think is what __attribute__ ((fallthrough)) will do. I'm not sure whether that will break things for earlier versions of the compiler though.

Similarly with the indentation in infer_scores.c. I'd rather fix that so the compiler doesn't complain. As it is written, the unusual indentation makes it clearer to the human reader what the intent of the code is. A series of five prints, the 3rd and 5th of which are controlled by a mode flag. I've got some ideas for how to convince the compiler to shut up about that. Will try them shortly.

My goal is that when the user compiles this, there will be no warnings, because the compiler will be vigilant and happy with everything.

**Comment by rsharris** [comment]
Could you try compiling now, with the unchanged Makefile?

I've added FALLTHRU comments as described at https://gcc.gnu.org/onlinedocs/gcc-7.1.0/gcc/Warning-Options.html#index-Wimplicit-fallthrough . 

For the indention in infer_scores.c, I've added empty comments in the space where the compiler would normally expect indentation. I suspect your compiler still might not like it. My compiler isn't complaining (but it wasn't complaining before the changes either).

Note that I don't know what compiler, or version of it, you are using.

**Comment by yanlinlin82** [comment]
Yes. '__attribute__((fallthrough));', which was introduced in gcc-7, did solve the problem.

BTW, I tried the following change in source code:

```
diff --git a/src/genpaf.c b/src/genpaf.c
index 12e9eb1..c5d9df1 100755
--- a/src/genpaf.c
+++ b/src/genpaf.c
@@ -853,6 +853,7 @@ void print_genpaf_align
 					break;
 					}
 				// (fall thru)
+				__attribute__((fallthrough));
 			case genpafStart2:
 				fprintf (f, unsposFmt, start2);
 				break;
@@ -863,6 +864,7 @@ void print_genpaf_align
 					break;
 					}
 				// (fall thru)
+				__attribute__((fallthrough));
 			case genpafStart2Zero:
 				fprintf (f, unsposFmt, start2-1);
 				break;
@@ -876,6 +878,7 @@ void print_genpaf_align
 					break;
 					}
 				// (fall thru)
+				__attribute__((fallthrough));
 			case genpafEnd2:
 				fprintf (f, unsposFmt, start2+len2-1);
 				break;
@@ -1538,6 +1541,7 @@ void print_genpaf_match
 					break;
 					}
 				// (fall thru)
+				__attribute__((fallthrough));
 			case genpafStart2:
 				fprintf (f, unsposFmt, start2);
 				break;
@@ -1548,6 +1552,7 @@ void print_genpaf_match
 					break;
 					}
 				// (fall thru)
+				__attribute__((fallthrough));
 			case genpafStart2Zero:
 				fprintf (f, unsposFmt, start2-1);
 				break;
@@ -1561,6 +1566,7 @@ void print_genpaf_match
 					break;
 					}
 				// (fall thru)
+				__attribute__((fallthrough));
 			case genpafEnd2:
 				fprintf (f, unsposFmt, start2-1 + length);
 				break;
diff --git a/src/utilities.c b/src/utilities.c
index 3ba990d..eb19936 100755
--- a/src/utilities.c
+++ b/src/utilities.c
@@ -1812,7 +1812,9 @@ u32 hassock_hash
 	switch (len)
 		{
 		case 3: h ^= *(--data) << 16;
+			__attribute__((fallthrough));
 		case 2: h ^= *(--data) << 8;
+			__attribute__((fallthrough));
 		case 1: h ^= *(--data);
 		        h *= m;
 		};
```

**Comment by rsharris** [comment]
Thanks. Unfortunately, "__attribute__((fallthrough));" is not recognized by all compilers (clang, for example).

I'm not sure what compilers recognize "/* FALLTHRU */", which is the solution in the source code now. Clang does. Gcc probably does, since its in their docs. I can't get to a machine with gcc at the moment to try it.

**Comment by rsharris** [comment]
It appears clang uses different syntax for this kind of thing -- "[[clang::fallthrough]];"
https://clang.llvm.org/docs/AttributeReference.html#fallthrough

**Comment by yanlinlin82** [comment]
I am using gcc-8.3.0, and I confirm that gcc does not recognize "/* FALLTHRU */" comment. I understand it is not easy to adapt to multiple compilers. How about using some precompiling conditional statements in source code to determine which compiler is currently using?

**Comment by rsharris** [comment]
Thanks for checking that.

Yep, some ifdefs based on compiler identity will be the next attempt. IIRC correctly I've got some other parts in the code doing that, or something like it.

**Comment by rsharris** [comment]
I've committed another attempt.

Utilities.c now defines "intentional_fall_thru" based on gcc and gcc version. This is similar to what I did to get gcc to stop complaining about intentionally unused function arguments. Also similar to a post at https://stackoverflow.com/questions/45349079/how-to-use-attribute-fallthrough-correctly-in-gcc .

It turns out that my compiler is sort of NOT clang. It's a version of clang pretending to be version 4.2.1 of gcc. I hadn't realized I was using something that old, version-wise, on this machine.

By the way, did my hack for misleading indentation satisfy your compiler?

**Comment by yanlinlin82** [comment]
No, I tried the latest version on GitHub (commit adf8247) and still got the following error:

```
gcc -c -O3 -Wall -Wextra -Werror -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DVERSION_MAJOR="\"1"\" -DVERSION_MINOR="\"04"\" -DVERSION_SUBMINOR="\"02"\" -DREVISION_DATE="\"20191010"\" -DSUBVERSION_REV="\""\" -Dscore_type=\'I\' infer_scores.c -o infer_scores.o
infer_scores.c: In function ‘infer_gap_scores’:
infer_scores.c:1191:2: error: this ‘else’ clause does not guard... [-Werror=misleading-indentation]
  else
  ^~~~
infer_scores.c:1193:3: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
   sOpen = (log(pOpen) - log(1-2*pOpen) + log(1-pExtend) - log(pExtend))
   ^~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:94: infer_scores.o] Error 1
make[1]: Leaving directory '/home/yanll/Downloads/lastz/src'
make: *** [Makefile:14: build_lastz] Error 2
```

I guess the compiler can not recognize that the program will abort in suicide(), and the following statements (lines 1192 and 1193 of `src/infer_scores.c`) do confuse people since they are on different levels (under 'else' or outside it).

**Comment by rsharris** [comment]
Wow!

That's exactly the type of problem that warning is supposed to catch. Clearly my intent was that statements 1192 through 1205 were part of the else clause. In this case it turns out to have been a benign screw up, but a screw up none the less.

I've submitted a correction, removing the else clause altogether.

**Comment by yanlinlin82** [comment]
That's great! Thanks!

**Comment by rsharris** [comment]
Thanks for reporting this, and thanks for your patience in testing my changes.

**Comment by rsharris** [comment]
The new tagged release 1.04.03 contains the fix for this.
