### ISSUE TITLE
very big genome

### ISSUE THREAD

**Issue by shenweima** [lastz/lastz#2]
The wheat genome is about 17Gb, the length of chromosome is ~700Mb.  I lastz_32 still can't work.
Can you increase this number?
```
lastz_32 IWGSCv1.fa[multiple] /data2/Fshare/FastaAndIndex/other_genomes_fasta/Kronos_EI_v1.fasta --step=16 --output=Cadenza.sam --format=sam --rdotplot=Cadenza.R --progress=1000 --gap=800,30

FAILURE: in load_fasta_sequence for IWGSCv1.fa, sequence length 4,013,315,000+750,843,639 exceeds maximum (4,294,967,285)
```

**Comment by lastz** [comment]
(Sorry for the delay in replying, for some reason github isn't sending me notifications for this repo)

Looking back through my emails, I see you contacted me directly after getting no response here.  Apparently we resolved the issue by resurrecting the settings to create a lastz_63 build.  I was not comfortable with that solution because it has not been well-tested and I expect it could lead to issues with runtime and memory.

My recommendation for other users who encounter this issue is to (conceptually) split their sequence into smaller pieces and run them as separate instances of the program.  This can be accomplished on the command line by attaching a subrange to the file name, as described here:
    http://www.bx.psu.edu/~rsharris/lastz/README.lastz-1.04.00.html#action_subrange

The best place to split sequences is in the middle of a run of Ns.  If that's not possible, then at a long softmasked segment, or at any segment where you don't expect alignment.  Non-aligning intervals can be found by running --ungapped (and not chained), merging all the aligned intervals and seeing where no alignment was reported.
