### ISSUE TITLE
The query end coordinates appears wrong when using both --format=blastn and  --nogapped

### ISSUE THREAD

**Issue by cmdcolin** [lastz/lastz#3]
I am aligning two individual sequences (can be single sequences) and using the `--format=blastn` flag and I was seeing some weird issues with the query end column

```
Scaffold0   NW_017371511.1  76.67   90  21  0   427927  428016  147620  14770990    4e-21   99.2
Scaffold0   NW_017371614.1  78.70   169 36  0   428123  428291  1965673 1965841169  6.3e-52 201.6
Scaffold0   NW_017371614.1  77.33   150 34  0   430511  430660  1968508 1968657150  8.6e-39 157.9
Scaffold0   NW_017371990.1  76.70   103 24  0   431458  431560  9126987 9127089103  2.9e-23 106.4
Scaffold0   NW_017371511.1  77.66   94  21  0   431774  431867  154538  15463194    9e-23   104.7
Scaffold0   NW_017371614.1  87.01   154 20  0   485732  485885  2022777 2022930154  1e-61   234.1
Scaffold0   NW_017371990.1  83.33   66  11  0   485765  485830  9329423 932948866   5e-16   82.3
Scaffold0   NW_017371614.1  84.26   413 65  0   489646  490058  2025995 2026407413  3e-173  604.6
Scaffold0   NW_017371563.1  64.17   120 43  0   495261  495380  3092573 3092692120  4.2e-10 62.6
Scaffold0   NW_017371614.1  79.60   201 41  0   495216  495416  2035916 2036116201  5.8e-69 258.2

```

It seems like the query end is way too big (e.g. 932948866?) but looking closer it seems like maybe it has extra numbers added onto the end e.g. query start 9329423 query end 9329488[66??]

I found this issue in 1.03.02 1.03.34 and lastz.v1.04.00 and it looks like it only happens if I use  both `--nogapped` and `--format=blastn` (if  `--nogapped` not specified, seems ok)

**Comment by lastz** [comment]
(Sorry for the delay in replying, for some reason github isn't sending me notifications for this repo)

It looks like you've made a PR for a fix for this.  I'll check that out (I'm not well-versed in github, and I haven't yet figured out how I can look at what you've changed).

**Comment by cmdcolin** [comment]
No worries, I think you just click "files changed" on the pull request, link https://github.com/lastz/lastz/pull/4/files

Just added a break statement :)

**Comment by lastz** [comment]
OK, I've looked at your fix now.  You're correct, there should be a break for the genpafEnd1Blast case, before the genpafLength1 case.  At line 1504 in genpaf.c.

I'll have to give some thought to how I want to manage pull requests, since github isn't the primary repository for this code.  I'll incorporate the change in the next tarball release, which will be reflected here.  But I might end up rejecting the PR.

Thanks for finding that, and again, my apologies for not replying way back in May.  I expected github would send me an email when an issue was opened.  From what I can find online, apparently it doesn't do that. Which means, I guess, that I would have to check the repo daily?). Please let me know if I'm wrong about all that.

**Comment by cmdcolin** [comment]
No worry, whatever works :)

I normally get pretty good email alerts from GitHub about activity, not exactly sure what setting controls it though. At least one setting is "watch" on each repo, normally you get automatically added to watch but you might add yourself https://github.com/lastz/lastz/watchers

**Comment by rsharris** [comment]
The latest commits to the main branch modify the source code in a way that should avoid that warning.

This change is not yet in a tagged release, but should be, soon.

**Comment by rsharris** [comment]
The new tagged release 1.04.03 contains the fix for this.
