### ISSUE TITLE
different results between lastz and blast

### ISSUE THREAD

**Issue by gorliver** [lastz/lastz#51]
Hi @rsharris ,
I'm using lastz (1.04.15) and blast to align a 90kb region; the results are pretty different. Here is an example that shows the alignment between 16000 to 17000 bp of my query sequences.
For lastz, I got:
```
tel     1       93.20   103     7       0       16055   16157   458139  458037  2.2e-42 169.9
tel     1       92.47   186     14      0       16172   16357   458361  458176  1.3e-83 306.8
tel     1       91.38   58      5       0       16357   16414   458417  458360  2.8e-17 86.4
tel     1       92.63   95      7       0       16426   16520   458535  458441  3e-37   152.8
tel     1       87.04   54      7       0       16526   16579   458589  458536  1.9e-12 70.4
tel     1       97.83   92      2       0       16922   17013   459076  458985  1.8e-41 166.8
```
For blast, I got:
```
tel     1       81.21   149     12      11      16107   16243   524632  524488  3e-20   106
tel     1       93.77   305     11      6       16501   16798   524276  523973  3e-124  451
tel     1       88.72   133     10      2       16845   16972   523966  523834  8e-36   158
```

The lastz command is:
```
lastz lyrata.fa tel.fa --format=BLASTN  --gfextend --nochain --nogapped --rdotplot=tel.r --step=20  > tel.lastz
```
I tried to tune the parameters like `gfextend`, `chain` and `gapped` but the alignments are still different from blast.
I wonder what I missed to run lastz?

**Comment by rsharris** [comment]
You certainly should use --gapped for this (rather than --nogapped). BLASTN allows gaps in the alignments it reports, and it is clear from column 7 that it has incorporated some gaps in those 3 alignments. (For format details, see https://lastz.github.io/lastz/#fmt_blastn ).

--chain doesn't seem warranted. --chain behaves like a synteny filter, and I don't think BLASTN gives any consideration to synteny. (To understand this, see figure 2f in this section: https://lastz.github.io/lastz/#options_chaining ).

That said, I wouldn't expect the alignments lastz reports to be identical to those BLASTN reports. For one thing, the scoring matrices aren't the same. That can be expected to cause minor differences in the placement of gaps and in the ends of aligned segments. BLASTN also includes an expectation filtering step not present in lastz. Because of this lastz may report some alignments that BLASTN thinks are not remarkable (such as alignments in repeats).

Also be aware that the e-value reported by lastz is a very crude approximation of the e-value that would be reported by BLASTN. This is indicated in the lastz documentation (same section as above). IIRC the approximation formula was derived by someone at UCSC circa 2003 (for lastz's predecessor blastz).

What's your use case here? It would seem that if you want BLASTN results you would just use BLASTN. AFAIK it's free to install it locally.

**Comment by gorliver** [comment]
Thank you for the explanation!
My use case is to find the syntenic region of my query sequence in the target species. I used to run blast and chain the HSP by brain.
What surprised me is that lastz mapped my 90kb sequence to 1:458037-459076  while blast mapped to 1:523834-524632 in the target species. The sequences of these two regions shows no similarity.

I then aligned these two regions to the query sequence and found that 1:523834-524632 mapped to 16-17kb on the query sequence, while 1:458037-459076 mapped to 72-73kb on my query. It seems the coordinates of lastz is for the reverse of the query?

**Comment by rsharris** [comment]
> It seems the coordinates of lastz is for the reverse of the query?

If they don't agree with `blastn -outfmt 7` that's a serious bug. I presume I tested that thoroughly when I added that format 10(?) years ago. But your report does suggest it is incorrect for negative strand alignments. I'm trying to find a spec for `blastn -outfmt 7` today but so far haven't found anything that would answer this question.

I'll try running some simple examples later today to see if I can resolve this.

**Comment by gorliver** [comment]
Please kindly let me know if you need my query sequence and the target genome.

**Comment by rsharris** [comment]
Thanks. For a test like this it will be easier for me to piece together random sequences so I'll know what the true answer should be.

The bigger issue is finding the time to do it. And figuring out how to set up command-line blastn. It's been a long time since I've run that and I'll need to check whether it's installed on the machine I use these days.

**Comment by gorliver** [comment]
Hi @rsharris , it's very likely that something happens on my side. If you need anything from me, just let me know.

**Comment by rsharris** [comment]
I sill haven't found a spec for `blastn -outfmt 7`, but my small test suggests lastz's `--format=blastn` reports q.start, q.end (in blastn lingo) incorrectly for alignments on the reverse strand.

Let me describe the test to see if I am missing something. The makeblastdb and blastn I use below report version as "2.8.1+".

I created (in lastz lingo) a 20K target and query by generating sequences per below. EchyDna just generates a random nt string of the given length, as an object that supports '+' as string concatenation and unary '-' as reverse complement. A similar sequence pair could be generated with other tools.
```
A1 = EchyDna(3000)
A2 = EchyDna(2000)
B  = EchyDna(4000)
C1 = EchyDna(3000)
C2 = EchyDna(2000)
D  = EchyDna(3000)
E1 = EchyDna(7000)
E2 = EchyDna(9000)

apple  = A1 + B + C1 +   D + E1
orange = A2 + B + C2 + (-D) + E2
```

I then aligned with lastz, using general output to verify that the alignments are where I would expect, and oriented the way I expect:
```
lastz apple.fa orange.fa --format=general:name1,zstart1,end1,name2,strand2,zstart2+,end2+

#name1 zstart1 end1 name2  strand2 zstart2+ end2+
APPLE  3000    7008  ORANGE +       2000     6008    <-- alignment 1
APPLE  9994    13000 ORANGE -       8000     11006   <-- alignment 2
(those coordinates are all along the forward strand)
```

And then used --format=blastn (boldface shows where the apparent error is):
```
lastz apple.fa orange.fa --format=blastn-

ORANGE APPLE 99.90 4008 4 0 2001 6008  3001  7008 0 7765.5   <-- alignment 1
ORANGE APPLE 99.93 3006 2 0 **8995 12000** 13000 9995 0 5820.0   <-- alignment 2
```

To run the same thing with blastn, I built a database from apple.fa:
```
makeblastdb -dbtype nucl -in apple.fa -parse_seqids
```

Then ran blastn:
```
blastn -task blastn -db apple.fa -query orange.fa -outfmt 7

# BLASTN 2.8.1+
# Query: ORANGE
# Database: apple.fa
# Fields: query acc.ver, subject acc.ver, % identity, alignment length, mismatches, gap opens, q. start, q. end, s. start, s. end, evalue, bit score
# 7 hits found
ORANGE APPLE 100.000 4000 0 0 2001  6000  3001  7000  0.0  7214   <-- alignment 1
ORANGE APPLE 99.933  3006 2 0 **8001  11006** 13000 9995  0.0  5413   <-- alignment 2
ORANGE APPLE 81.081  37   4 2 11240 11273 2976  2940  0.34 30.1
ORANGE APPLE 100.000 15   0 0 13626 13640 1732  1746  1.2  28.3
ORANGE APPLE 94.118  17   1 0 8055  8071  2414  2430  4.1  27.4
ORANGE APPLE 94.118  17   1 0 18260 18276 16899 16883 4.1  27.4
ORANGE APPLE 94.118  17   1 0 19621 19637 18139 18155 4.1  27.4
# BLAST processed 1 queries
```

So it does look like lastz is reporting the position of the query along the forward strand, whereas blastn appears to report it along the aligning strand.

It won't make much to fix that in lastz. But I'd feel a lot better if I could find a spec for that blastn format, so I'm going to hunt a little more for that. And run some additional tests.

Thanks for finding this.

**Comment by rsharris** [comment]
I guess **boldface** doesn't come out as boldface.

**Comment by rsharris** [comment]
> But I'd feel a lot better if I could find a spec for that blastn format, so I'm going to hunt a little more for that.

Well, I found the BLAST® Command Line Applications User Manual. Sadly, what it says about these four fields is less than illuminating
```
qstart means Start of alignment in query
qend means End of alignment in query
sstart means Start of alignment in subject
send means End of alignment in subject
```

**Comment by rsharris** [comment]
> So it does look like lastz is reporting the position of the query along the forward strand, whereas blastn appears to report it along the aligning strand.

My statement above is incorrect. It should say blastn always reports the position of the query along the forward strand. And lastz (currently) is reporting it along the aligning strand.

Blast customer support confirms that.

I've fixed that in the current main branch. I will need to do further tests and tag a release. Tagging a release involves a lot of time consuming stuff, like updated the readmes and release notes. I'll also have to figure out how to notify users on the official mailing list because that list server is currently down. Not sure how quickly I will accomplish all that.

**Comment by gorliver** [comment]
Thank you for the detailed analysis.
 It makes sense to me and I can the coordinates of reverse alignment of my sequence.
Looking forwards to your new version.

**Comment by rsharris** [comment]
The new tagged release 1.04.22 contains the fix for this.
