### ISSUE TITLE
Question about maf_sort.py

### ISSUE THREAD

**Issue by 4ureliek** [lastz/lastz#6]
Hi,
I have been looking for an alternative to the [dentearl/mafTools/mafSorter](https://github.com/dentearl/mafTools/tree/master/mafSorter) that is not working on some very large files, but it is not clear to me how your maf_sort.py sorts the blocks in the maf file: if it is like mafTools, how is the species that is used to sort the coordinates set?
Thank you!
Cheers,
Aurelie

**Comment by lastz** [comment]
(Sorry for the delay in replying, github hasn't been sending me notifications for this repo)

Be aware that the contents of the lastz/tools subdirectory are not intended to be general purpose tools.  Some might be generally useful, but in the case of maf_sort, the only reason it's there is to support some unit tests (which, as another issue reveals, aren't actually included in the repo).

It's been at least 8 years since I looked at maf_sort. ... let's see ... looking at the source code ... looks like it very much expects the MAF to have been written by lastz. For one thing, it expects only pairwise MAF.  Doesn't know much about species names. It might also have problems with large files, since it reads the entire maf file into a python list before sorting it. Useful to facilitate comparison of two small MAF files that might have a different order. Not useful in the general case.

**Comment by 4ureliek** [comment]
Thank you very much for this answer - I understand better why it did not like my multispecies maf file...!
